### ISSUE TITLE
Calc quota has hardcoded 'base_image'

### ISSUE THREAD

**Issue by acampsm** [Calipsoplus/calipsoplus-frontend#81]
If the 'base_image' not exists in image db table, the application exits to the home page of calipsoplus.

**Comment by acampsm** [comment]
We also remove the "default image" quota column from quotas layout because is not necessary.

**Comment by aicampbell** [comment]
It might be a good idea to also remove the base_image_ubuntu and replace it with the new base image I created which has the username:password, uid, gid as well as VNC and RDP

**Comment by acampsm** [comment]
sure
